sudo: required
language: python
python:
  - "3.6"

services:
  - docker

install:
  - echo "install nothing"

script:
  - echo "no tests"

after_success:
  - docker --version
  - pip install awscli
  - export PATH=~/.local/bin:$PATH
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t sdc .
  - docker tag sdc:latest $ECR_ID.dkr.ecr.us-east-1.amazonaws.com/sdc:latest
  - docker push $ECR_ID.dkr.ecr.us-east-1.amazonaws.com/sdc:latest
